# Secrets file
#
# Store Zendesk user names and tokens in the following environment variables to make them avaiable within the application:
# ZENDESK_ADMIN_USER: the user account to use for searching Zendesk
# ZENDESK_ADMIN_TOKEN: a security token used to login to that account
#
# The application's secret key base should be stored in:
# SECRET_KEY_BASE

development:
  secret_key_base:    		88d1728eff3b716187899beb87623fa73fcac594f7cbd7a431f98b53316c2b5039c5da65b8eac9d2bd9559d541c3453fde359b486f398dbb55069611117acdae
  zendesk_admin_user: 		<%= ENV["ZENDESK_ADMIN_USER"] %>
  zendesk_admin_token:		<%= ENV["ZENDESK_ADMIN_TOKEN"] %>

test:
  secret_key_base:			0c98e9032efe0f749757261be2b09403763c202468e280c73321e3036ad27c60838dd5cf051286398567ef5b7f535aee22f56ccd9eb36675316cfc1148c1bc23
  zendesk_admin_user: 		
  zendesk_admin_token:		

production:
  secret_key_base:			<%= ENV["SECRET_KEY_BASE"] %>
  zendesk_admin_user:		<%= ENV["ZENDESK_ADMIN_USER"] %>
  zendesk_admin_token:		<%= ENV["ZENDESK_ADMIN_TOKEN"] %>